### ISSUE TITLE
Rule proposal: Enforce blank lines around tests

### ISSUE THREAD

**Issue by jdoubleu** [lo1tuma/eslint-plugin-mocha#185] opened 2018-12-18 22:26 UTC
It would be nice to have a rule which enforces blank links around `it()` test statements.

I expect the rule to disallow:
```
...
it('should do something', () => {
  ...
})
it('should test other thing', () => {
})
```

But allows:
```
...
it('should do something', () => {
  ...
})

it('should test other thing', () => {
})
```

This is similar to the [`padding-line-between-statements` ESLint rule](https://eslint.org/docs/rules/padding-line-between-statements) but is more specific about the statement (i.e. `it()` function call).

**Comment by lo1tuma** [comment] 2020-02-19 11:27
Duplicate of #145.

**Closed by lo1tuma** 2020-02-19 11:27 UTC
